
module.exports = [
	'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-cookies.min.js'
	'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-route.min.js'
	'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-sanitize.min.js'
	'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js'
	'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'
	'https://cdn.rawgit.com/angular-ui/ui-ace/36844ff7c0e0d9445bc8e31514d7f0f59cb8b048/ui-ace.min.js'
	'https://cdn.rawgit.com/Hypercubed/angular-marked/1b0a4ef682cbdece294db8225db8e81a775acc6b/angular-marked.min.js'
	'https://cdn.rawgit.com/RickStrahl/json.date-extensions/eab6ebf5a6ee61c7f8c2c2af71d978dbf7fdf22c/json.date-extensions.min.js'
	'https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/ace.js'
	'https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/mode-markdown.js'
	'https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.2/mode-c_cpp.js'
	'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap-tpls.min.js'
	'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.js'
	'https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'
	'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js'
	'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css'
	'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap-theme.min.css'
	'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/fonts/glyphicons-halflings-regular.eot'
    'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/fonts/glyphicons-halflings-regular.svg'
    'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/fonts/glyphicons-halflings-regular.ttf'
    'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/fonts/glyphicons-halflings-regular.woff'
    'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/fonts/glyphicons-halflings-regular.woff2'
    'https://cdnjs.cloudflare.com/ajax/libs/angular-smart-table/2.1.6/smart-table.min.js'
]
